apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-helm-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 9526584898/nodeapphelm
        ports:
        - containerPort: 8080
